# --- Streamlit Secrets for APMT ---
# Place this file at one of these paths:
# C:\Users\dkeya\.streamlit\secrets.toml
# C:\Users\dkeya\Documents\SBS\2025\APMT\.streamlit\secrets.toml

# Get a token from https://account.mapbox.com/ (Access tokens → Default public token)
MAPBOX_TOKEN = "pk.your_real_mapbox_token_here"

# (Optional) other app-level secrets/paths you might want later:
# DATA_PATH = "C:\\Users\\dkeya\\Documents\\SBS\\2025\\APMT\\APMT_Longitudinal_Survey.csv"
# MAP_STYLE = "mapbox://styles/mapbox/light-v10"
